### ISSUE TITLE
Template sources missing

### ISSUE THREAD

**Issue by shezaan** [githubixx/ansible-role-kubernetes-worker#6]
I maybe wrong, but its seems like the template sources on line 156 and 166 of tasks/main.yml are missing.

**Comment by githubixx** [comment]
The file is generated in a different playbook. Have a look here: https://github.com/githubixx/ansible-kubernetes-playbooks/tree/master/kubeauthconfig. Also have a look at my blog: https://www.tauceti.blog/post/kubernetes-the-not-so-hard-way-with-ansible-at-scaleway-part-4/ (search for "kubeconfig").
