### ISSUE TITLE
k8s_kubelet_token

### ISSUE THREAD

**Issue by shezaan** [githubixx/ansible-role-kubernetes-worker#7]
The kubeconfig template file uses token: {{k8s_kubelet_token}}. Is it still required given that RBAC will be used?
BTW, loved your blog. Great step by step instructions and I would still call it Kubernetes the hard way.... just... automated. Great implementation/automation of Kelsey Hightower's instructions.

**Comment by githubixx** [comment]
Thanks for the hint! Not only the the token isn't needed anymore the whole template file isn't needed anymore :wink: I updated the role accordingly. That was a leftover from times before Kubernetes 1.6 or so. The kubeconfig files for the worker are created here: https://github.com/githubixx/ansible-kubernetes-playbooks/blob/master/kubeauthconfig/kubelets.yml. The worker authenticate via a client certificate.
