### ISSUE TITLE
Task "install some network packages" using deprecated state

### ISSUE THREAD

**Issue by WilliamCocker** [githubixx/ansible-role-kubernetes-worker#8]
FYI, the task "Install some network packages" is using the deprecated "installed" state instead of "present":

![screen shot 2018-05-25 at 14 55 23](https://user-images.githubusercontent.com/37018962/40545375-e7c3186c-602b-11e8-86ee-dfa0f3c2a18e.png)

I'm slowly but surely going forward with your k8s tutorial! I've had to adjust a few things to get it to work on a LXD 3.1 cluster (using a fan network instead of PeerVPN). It's pretty neat so far, I have 9 instances (3 etcd, 3 controllers and 3 workers) running on 3-servers LXD cluster (to simulate 3 availability zones). It's more convenient to break things and go back, the snapshots and restore are much faster (and cheaper) than on cloud instances... I'll document something when I'm done with the whole thing (that's hoping I succeed of course...).

**Comment by githubixx** [comment]
Thx for reporting! Fixed with r4.1.1_v1.9.3. 

IMHO the whole networking thingy you need for K8s is one of the hardest parts of the whole stack. If you get this working you basically already made it ;-)

**Comment by WilliamCocker** [comment]
Ok great and thanks to you!

I'm actually stuck on this setup, there are legacy kernel modules not available in LXD system containers that prevent the k8s cluster from properly initialising (the kube-proxy and kubelet services fail so start due to those missing modules). However if I use the "Canonical distribution of k8s" with the very same containers then I have no problem... it seems they have tuned it for LXD compatibility. But since I want to learn and install everything myself I don't want to rely on juju charms for the setup. I'm back to using VMs for now and I'll probably end up on scaleway instances once I'm mostly comfortable with the whole stack.
